AWSTemplateFormatVersion: '2010-09-09'
Description: Parent stack for the network and compute stacks in Project2
Resources:
  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://awsproject1-ludtke.s3.amazonaws.com/project2-network-ludtke.yaml
  ComputeStack:
    Type: AWS::CloudFormation::Stack
    #DependsOn:
    #  - "NetworkStack"
    Properties:
      TemplateURL: https://awsproject1-ludtke.s3.amazonaws.com/project2-compute-ludtke.yaml
      Parameters:
        NetworkStackName: !GetAtt 
        - NetworkStack
        - Outputs.NetworkStackName

Outputs:
  NetworkStackName:
    Value: !Ref NetworkStack
  ComputeStackName:
    Value: !Ref ComputeStack
  OutputFromNestedStack:
    Value: !GetAtt 
      NetworkStack.Outputs.awsproject1-ludtke
      ComputeStack.Outputs.awsproject1-ludtke