AWSTemplateFormatVersion: '2010-09-09'
Description: Parent stack for the network and compute stacks in Project2
Resources:
  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://awsproject1-ludtke.s3.amazonaws.com/project2-network-ludtke.yaml
  ComputeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://awsproject1-ludtke.s3.amazonaws.com/project2-compute-ludtke.yaml
      Parameters:
        NetworkStackName: !GetAtt 
        - NetworkStack
        - Outputs.NetworkStackName
        VPC: !GetAtt 
        - NetworkStack
        - Outputs.VPC
        PrivateSubnet1: !GetAtt 
        - NetworkStack
        - Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt 
        - NetworkStack
        - Outputs.PrivateSubnet2
        PublicSubnet1: !GetAtt 
        - NetworkStack
        - Outputs.PublicSubnet1
        PublicSubnet2: !GetAtt 
        - NetworkStack
        - Outputs.PublicSubnet2
        WebInstanceSecurityGroup: !GetAtt 
        - NetworkStack
        - Outputs.WebInstanceSecurityGroup
        ALBSecurityGroup: !GetAtt 
        - NetworkStack
        - Outputs.ALBSecurityGroup
        NATSecurityGroup: !GetAtt 
        - NetworkStack
        - Outputs.NATSecurityGroup
        BastionHostSecurityGroup: !GetAtt 
        - NetworkStack
        - Outputs.BastionHostSecurityGroup

Outputs:
  NetworkStackName:
    Value: !Ref NetworkStack
  ComputeStackName:
    Value: !Ref ComputeStack
  OutputFromNestedStack:
    Value: !GetAtt 
      NetworkStack.Outputs.awsproject1-ludtke
      ComputeStack.Outputs.awsproject1-ludtke