AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy EC2 instances and ALB for Project 1

Parameters:
# Need to ask user for name of network stack
  NetworkStackName:
    Type: AWS::EC2::Image::Id
    Description: test-project1network-ludtke

Resources:

# Optional BastionHostInstance would go here

  WebServerInstance1:

# When you create these resources you'll need to reference values that were exported from stack #1
# One example would be the Private Subnet ID for placing WebServerInstance1 on
# This should look SOMETHING like this in my example from class:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-07eb8c4d4db8d4cb1"
      KeyName: "project1"
      SubnetId:
        Fn::ImportValue:
          Fn::Sub: "${test-project1network-ludtke}-PrivateSubnet1"
      SecurityGroups:
        Fn::ImportValue:
          Fn::Sub: "${test-project1network-ludtke}-WebInstanceSecurityGroupIngress"

  WebServerInstance2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-07eb8c4d4db8d4cb1"
      KeyName: "project1"
      SubnetId:
        Fn::ImportValue:
          Fn::Sub: "${test-project1network-ludtke}-PrivateSubnet2"
      SecurityGroups:
        Fn::ImportValue:
          Fn::Sub: "${test-project1network-ludtke}-WebInstanceSecurityGroupIngress"

  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
        DefaultActions:
            - Type: accept
        LoadBalancerArn: 
        Port: 80
        Protocol: tcp
    #no imports needed

  ALBTargetGroup:
    Type: AWS::ElasticLoadBalncingV2::TargetGroup
    Properties:
      VpcId: 
        Fn::ImportValue:
          Fn::Sub: "${test-project1network-ludtke}-VPCId"
    #needs import for vpc id

  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalncingV2::LoadBalancer
    Properties:
      ALBSG: 
        Fn::ImportValue:
          Fn::Sub: "${test-project1network-ludtke}-ALBSGId"
      PubSub1: 
        Fn::ImportValue:
          Fn::Sub: "${test-project1network-ludtke}-PubSub1Id"
      PubSub2: 
        Fn::ImportValue:
          Fn::Sub: "${test-project1network-ludtke}-PubSub2Id"
    #needs import value of the alb sg id
    #needs imports for both public subnets

Outputs:
# This is an example of the complete YAML code for outputting the VPC information and also exporting the VPC ID for use
# by another template
  ApplicationLoadBalancer:
# Need the DNS/URL of the ApplicationLoadBalancer
    Description: DNS Address
    Value: 
      Fn::GetAtt:
        - ApplicationLoadBalancer
        - DNSName
